# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 16:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0002_auto_20160819_1044'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='trip',
            managers=[
                ('tripManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
